### ISSUE TITLE
can't run check

### ISSUE THREAD

**Issue by benji822** [CheckiO/checkio-client#13]
Hi, I'm following the instruction, but when i try to run check i get this error
![image](https://user-images.githubusercontent.com/28833820/73422638-8ecfe000-4364-11ea-9116-dda07a9177ca.png)

**Comment by mayank-m2** [comment]
try:
```shell
$ checkio --domain js check median
```

**Comment by ghislain-bernard** [comment]
Similar problem to https://github.com/CheckiO/checkio-client/issues/12 ... impossible to run check in js domain.

**Comment by D3SL** [comment]
I get the same error in windows 10 for the python domain, including when trying ```checkio --domain py check <mission>```.

**Comment by oduvan** [comment]
for ssl exception do the following on mac `/Applications/Python\ 3.6/Install\ Certificates.command`

also, try to upgrade checkio-client

**Comment by hbxz** [comment]
If you get a `404`, it might be triggered by naming mismatch. 
e.g. 
- `checkio check multiply-intro`  gets you want.
- `checkio check multiply_intro.js` or `checkio check multiply_intro` gets `404`. 

> notice the `.js` and difference between `_` and `-`. 
> The `check` expects `-` rather than `_` on words separation, while `js` files use `_`. 
> This error can happen when you use `tab` to save time. Though I do like to have such feature on naming tolerance.

**Comment by hbxz** [comment]
I add the following lines to line 201 in `runner.py` to enjoy the "feature" I mention above. 

> I bet it's not good practice to do this. 

```python
    def formalize_mission(args):
        if "mission" in args:
            args.mission[0] = args.mission[0].split(".")[0].replace("_", "-")
            # e.g "hello_world.js" => "hello-world"
    formalize_mission(args)
```

Now, this code looks like this:

```python
def main():

    # because of calling inside of #!/usr/bin/
    call_args = sum(map(lambda a: shlex.split(a), sys.argv[1:]), [])
    args = parser.parse_args(call_args)

    logging.basicConfig(level=LEVELS[args.verbose])

    # because I don't knoe how to get log_level from logging
    logging.log_level = LEVELS[args.verbose]

    def formalize_mission(args):
        if "mission" in args:
            args.mission[0] = args.mission[0].split(".")[0].replace("_", "-")
            # e.g "hello_world.js" => "hello-world"
    formalize_mission(args)
    # .......
```

**Comment by oduvan** [comment]
> checkio check multiply_intro.js

is not working yet, but I [plan](https://github.com/CheckiO/checkio-client/issues/16) to implement this one

**Comment by oduvan** [comment]
fixed
