### ISSUE TITLE
First sync missing backslashes in folder path [windows]

### ISSUE THREAD

**Issue by Philippe-Cholet** [CheckiO/checkio-client#17]
@oduvan For backup, I synced today (in a new private github repo located in my dropbox).

First sync `checkio sync "P:\Dropbox\Python\py-checkio-solutions"` synced solutions in `"P:\DropboxPythonpy-checkio-solutions"`, without backslashes.
I updated `.checkio\config.ini`, did `checkio sync` and it was (still long but) good this time.

I searched why `\`s vanished but I failed. I think it has something to do with the parser, it is quite complicated.

PS: I use checkio-client 0.2.9 (so up to date), Python 3.7.4, windows 10.
And I don't think it is relevant but I installed it with pipx: `pipx install checkio-client`

**Comment by oduvan** [comment]
should be fixed now
