### ISSUE TITLE
Running using the shebang line is broken because of Line 192 in runner.py (Windows)

### ISSUE THREAD

**Issue by NitrousWolf** [CheckiO/checkio-client#20]
See comments on https://py.checkio.org/blog/new-tool-checkio-client/#comment-96651 for original report

I found that it was impossible to run the solution with the 2nd suggested command:
`checkio_solutions/median.py --check`

Workaround:
running using the 1st suggested command works fine
`checkio init median checkio_solutions/median.py`

Possible Fix?:
replace
`call_args = sum(map(lambda a: shlex.split(a), sys.argv[1:]), [])`
with
`call_args = sys.argv[1:]`

**Comment by oduvan** [comment]
fixed. Thank you
