### ISSUE TITLE
Install/Upgrade fails because setup.py can't find requirements.txt

### ISSUE THREAD

**Issue by NitrousWolf** [CheckiO/checkio-client#21]
Error after running pip install -U checkio_client

`WARNING: Discarding https://files.pythonhosted.org/packages/7b/cc/a1a41b24c3236dffa740fd5d1318d755dbb0982d9749a400cca268f70f48/checkio_client-0.2.12.tar.gz#sha256=fb8db5471646daa21c1fa95b98
442175d0e800d6c0c96f1fff7b5cc89d149bed (from https://pypi.org/simple/checkio-client/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the log
s for full command output.
  Created temporary directory: C:\Users\Nick\AppData\Local\Temp\pip-unpack-ki4a5pp1
  Looking up "https://files.pythonhosted.org/packages/c3/e0/1343385526fe916bc22202944aab306417056ab407a57c7a5fd1b046fb9b/checkio_client-0.2.11.tar.gz" in the cache
  Current age based on date: 3065
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 3065
  Using cached checkio_client-0.2.11.tar.gz (33 kB)
  Added checkio_client from https://files.pythonhosted.org/packages/c3/e0/1343385526fe916bc22202944aab306417056ab407a57c7a5fd1b046fb9b/checkio_client-0.2.11.tar.gz#sha256=391892caca9d2e0fc0
f74b99da88df7ef50c8e9509e33a214520dfee42b3576c to build tracker 'C:\\Users\\Nick\\AppData\\Local\\Temp\\pip-req-tracker-cqttdg23'
    Running setup.py (path:C:\Users\Nick\AppData\Local\Temp\pip-install-jvlysbci\checkio-client_4e8a3a05277e4034b23c6aca2076ead0\setup.py) egg_info for package checkio-client
    Created temporary directory: C:\Users\Nick\AppData\Local\Temp\pip-pip-egg-info-8n50nex4
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Nick\AppData\Local\Temp\pip-install-jvlysbci\checkio-client_4e8a3a05277e4034b23c6aca2076ead0\setup.py", line 5, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
`

Possible Fix?:
Seems to be a common problem, the requirements.txt is actually checkio_client.egg-info/requires.txt

I found https://stackoverflow.com/questions/42530309/no-such-file-requirements-txt-error-while-installing-quartz-module

![requirements](https://user-images.githubusercontent.com/50035708/107414558-1456a600-6b0a-11eb-8d17-a1a2b02a3f50.PNG)

I unzipped checkio_client-0.2.12.tar.gz and modified line 5 of setup.py from 
`with open('requirements.txt') as f:`
to 
`with open('checkio_client.egg-info/requires.txt') as f:`
then checked that it worked by running 
`pip install -e C:\Users\Nick\Downloads\checkio\checkio_client-0.2.12`
install succeeded and "pip list" showed that 0.2.12 was installed :)

More info:
Looks like this issue arose now because the .WHL file was not present for the last 2 versions whereas it was previously being used to successfully install via pip
![repo](https://user-images.githubusercontent.com/50035708/107414959-a2329100-6b0a-11eb-8506-46f4f9dd9275.PNG)

**Comment by oduvan** [comment]
.WHL - should be added. Can you plz check?

**Comment by NitrousWolf** [comment]
Thanks, it looks like your new .whl is now there however it won't install for me still. The new problem is tagging it appears


```
  Skipping link: none of the wheel's tags match: py2-none-any: https://files.pythonhosted.org/packages/11/6a/fc6dc1668ce8e90068b7c24d22e7894a455988a4d21da943b643a009d6d0/checkio
_client-0.2.12-py2-none-any.whl#sha256=ab363daf3af4bdce05aa2491624822a4522d34a41a512b78c5cb390ef959b26e (from https://pypi.org/simple/checkio-client/) (requires-python:>=3.6)

```


![Capture](https://user-images.githubusercontent.com/50035708/107849585-2aa77f00-6df4-11eb-9a85-c38c5f01f7da.PNG)

**Comment by oduvan** [comment]
Add a new wheel for py3.

Can you check again?

Thank you.

**Comment by NitrousWolf** [comment]
All good! Thank you.
![Capture](https://user-images.githubusercontent.com/50035708/107850172-59bfef80-6df8-11eb-9ef5-0a6cb0ba0d25.PNG)

**Comment by oduvan** [comment]
Thank you for helping me out!
