### ISSUE TITLE
checkio command not found

### ISSUE THREAD

**Issue by jakern** [CheckiO/checkio-client#8]
Kubuntu 18.10
Python 3.6.7

Installing from PyPI and GitHub seemed to work fine but in both cases checkio command could not be found in zsh and bash.

**Comment by oduvan** [comment]
@jakern 

thanks for report.

I'll try to replicate on out side this issue but looks like default setup configuration works not for all cases.

Can you try the same step in virtualenv?

Thanks a lot.

**Comment by jakern** [comment]
Thanks! venv worked.
